export const COUNTRY_PREFIXES = [
  { prefix: '971', country: 'UAE' },
  { prefix: '966', country: 'Saudi Arabia' },
  { prefix: '968', country: 'Oman' },
  { prefix: '974', country: 'Qatar' },
  { prefix: '973', country: 'Bahrain' },
  { prefix: '965', country: 'Kuwait' },
  { prefix: '44', country: 'UK' },
  { prefix: '1', country: 'USA/Canada' },
  { prefix: '91', country: 'India' },
  { prefix: '92', country: 'Pakistan' },
  { prefix: '33', country: 'France' },
  { prefix: '49', country: 'Germany' },
  { prefix: '39', country: 'Italy' },
  { prefix: '34', country: 'Spain' },
  { prefix: '31', country: 'Netherlands' },
  { prefix: '32', country: 'Belgium' },
  { prefix: '41', country: 'Switzerland' },
  { prefix: '86', country: 'China' },
  { prefix: '81', country: 'Japan' },
  { prefix: '82', country: 'South Korea' },
  { prefix: '61', country: 'Australia' },
  { prefix: '64', country: 'New Zealand' },
  { prefix: '27', country: 'South Africa' },
  { prefix: '55', country: 'Brazil' },
  { prefix: '52', country: 'Mexico' },
  { prefix: '7', country: 'Russia' },
  { prefix: '90', country: 'Turkey' },
  { prefix: '62', country: 'Indonesia' },
  { prefix: '63', country: 'Philippines' },
  { prefix: '60', country: 'Malaysia' },
  { prefix: '66', country: 'Thailand' },
  { prefix: '84', country: 'Vietnam' },
  { prefix: '20', country: 'Egypt' },
  { prefix: '234', country: 'Nigeria' },
  { prefix: '254', country: 'Kenya' },
  { prefix: '46', country: 'Sweden' },
  { prefix: '47', country: 'Norway' },
  { prefix: '45', country: 'Denmark' },
  { prefix: '358', country: 'Finland' },
  { prefix: '48', country: 'Poland' },
  { prefix: '43', country: 'Austria' },
  { prefix: '353', country: 'Ireland' },
  { prefix: '351', country: 'Portugal' },
  { prefix: '30', country: 'Greece' },
  { prefix: '380', country: 'Ukraine' },
  { prefix: '40', country: 'Romania' },
  { prefix: '36', country: 'Hungary' },
  { prefix: '420', country: 'Czech Republic' },
  { prefix: '962', country: 'Jordan' },
  { prefix: '961', country: 'Lebanon' },
  { prefix: '964', country: 'Iraq' },
  { prefix: '98', country: 'Iran' },
  { prefix: '994', country: 'Azerbaijan' },
  { prefix: '995', country: 'Georgia' },
].sort((a, b) => b.prefix.length - a.prefix.length)

export function getCountryFromPhone(phone?: string | null): string {
  if (!phone) return 'Unknown'
  const clean = phone.replace(/[^0-9]/g, '')
  for (const entry of COUNTRY_PREFIXES) {
    if (clean.startsWith(entry.prefix)) return entry.country
  }
  return 'Unknown'
}
